### ISSUE TITLE
Change viewSwitcher.js Source

### ISSUE THREAD

**Issue by KevinGimbel** [Haroenv/cv#1]
Hey! 

Just noticed you are using the viewSwitcher.js from my site (http://kevingimbel.com/viewSwitcher/src/viewswitcher.js) - you should better download it and pack it with this repository. If I delete or rename the file your CV breaks. 

Btw, really like your CV. Looks good and I'm happy you're using my script :smile:

**Comment by Haroenv** [comment]
Thanks, I'll do it ASAP :)
